---
- name: Converge
  hosts: all
  roles:
    - role: secrets_info
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: apps
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: secrets
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - secrets_info
...
