---
- name: Ensure flyio secrets are managed
  tags:
    - secrets
  no_log: "{{ secrets_no_log }}"
  linuxhq.flyio.secrets:
    api_token: "{{ secrets_api_token }}"
    app_name: "{{ _secret.0.app_name }}"
    name: "{{ _secret.1.name }}"
    state: "{{ _secret.1.state | d(_secret.0.state | d('present')) }}"
    value: "{{ _secret.1.value | d(omit) }}"
  register: __secrets_result
  loop: "{{ __secrets_list }}"
  loop_control:
    label: "{{ _secret.1.name | d(none) }}"
    loop_var: _secret
  async: "{{ ansible_check_mode | ternary(0, secrets_async) }}"
  poll: "{{ secrets_poll }}"
  when:
    - secrets_api_token is not none
    - _secret.0.app_name is defined
    - _secret.1.name is defined
  changed_when:
    - ansible_check_mode | bool
    - __secrets_result.changed | bool

- name: Ensure managed flyio secret jobs are complete
  tags:
    - secrets
  no_log: "{{ secrets_no_log }}"
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __secrets_status
  loop: "{{ __secrets_result.results }}"
  loop_control:
    label: "{{ _jid._secret.1.name | d(none) }}"
    loop_var: _jid
  when:
    - _jid.ansible_job_id is defined
  until:
    - __secrets_status.finished | bool
  retries: "{{ secrets_retries }}"
  delay: "{{ secrets_delay }}"
...
