---
- name: Ensure flyio secrets are batched
  tags:
    - secrets
  ansible.builtin.include_tasks:
    apply:
      tags:
        - secrets
    file: include.yml
  loop:
    "{{ q('ansible.builtin.subelements',
          secrets_list,
          'secrets',
          {'skip_missing': true}) |
        batch(secrets_batch) }}"
  loop_control:
    label: "{{ __secrets_list | length }}"
    loop_var: __secrets_list
...
