---
- name: Ensure flyio machines are managed
  tags:
    - machines
  linuxhq.flyio.machines:
    api_token: "{{ machines_api_token }}"
    app_name: "{{ _machine.0.app_name }}"
    auto_destroy: "{{ _machine.1.auto_destroy | d(omit) }}"
    checks: "{{ _machine.1.checks | d(omit) }}"
    env: "{{ _machine.1.env | d(omit) }}"
    files: "{{ _machine.1.files | d(omit) }}"
    guest: "{{ _machine.1.guest | d(omit) }}"
    id: "{{ _machine.1.id | d(omit) }}"
    image: "{{ _machine.1.image | d(omit) }}"
    init: "{{ _machine.1.init | d(omit) }}"
    metadata: "{{ _machine.1.metadata | d(omit) }}"
    mounts: "{{ _machine.1.mounts | d(omit) }}"
    name: "{{ _machine.1.name | d(omit) }}"
    region: "{{ _machine.1.region | d(omit) }}"
    restart: "{{ _machine.1.restart | d(omit) }}"
    services: "{{ _machine.1.services | d(omit) }}"
    statics: "{{ _machine.1.statics | d(omit) }}"
    state: "{{ _machine.1.state | d(_machine.0.state | d('present')) }}"
    wait: "{{ _machine.1.wait | d(omit) }}"
    wait_timeout: "{{ _machine.1.wait_timeout | d(omit) }}"
  register: __machines_result
  loop: "{{ __machines_list }}"
  loop_control:
    label: "{{ _machine.1.name | d(none) }}"
    loop_var: _machine
  async: "{{ ansible_check_mode | ternary(0, machines_async) }}"
  poll: "{{ machines_poll }}"
  when:
    - machines_api_token is not none
    - _machine.0.app_name is defined
    - _machine.1.name is defined or
      _machine.1.id is defined
  changed_when:
    - ansible_check_mode | bool
    - __machines_result.changed | bool

- name: Ensure managed flyio machine jobs are complete
  tags:
    - machines
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __machines_status
  loop: "{{ __machines_result.results }}"
  loop_control:
    label: "{{ _jid._machine.1.name | d(none) }}"
    loop_var: _jid
  when:
    - _jid.ansible_job_id is defined
  until:
    - __machines_status.finished | bool
  retries: "{{ machines_retries }}"
  delay: "{{ machines_delay }}"
...
