---
- name: Converge
  hosts: all
  roles:
    - role: apps
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: secrets
      secrets_list: []
      tags:
        - molecule-idempotence-notest

    - secrets
...
