---
- name: Converge
  hosts: all
  roles:
    - role: apps
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: volumes
      volumes_list: []
      tags:
        - molecule-idempotence-notest

    - volumes
...
