---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        volumes_api_token: "{{ lookup('env', 'FLY_API_TOKEN') }}"
        volumes_app_name: molecule-test-app
        volumes_list:
          - name: molecule_data
            region: ord
            size_gb: 1

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
