---
dependencies: []
galaxy_info:
  role_name: ip_addresses
  author: Taylor Kimball
  description: Manage Fly.io IP addresses
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - flyio
    - ip
    - network
...
