---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: localhost

provisioner:
  name: ansible
  env:
    ANSIBLE_ACTION_WARNINGS: false
    ANSIBLE_DEPRECATION_WARNINGS: false
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        apps_api_token: "{{ lookup('env', 'FLY_API_TOKEN') }}"
        apps_list:
          - name: molecule-test-app
            org_slug: "{{ lookup('env', 'FLY_ORG_SLUG') }}"

        machines_api_token: "{{ lookup('env', 'FLY_API_TOKEN') }}"
        machines_info_api_token: "{{ lookup('env', 'FLY_API_TOKEN') }}"
        machines_info_app_name: molecule-test-app
        machines_list:
          - app_name: molecule-test-app
            machines:
              - guest:
                  cpu_kind: shared
                  cpus: 1
                  memory_mb: 256
                image: nginx:alpine
                name: molecule-web
                region: ord
              - guest:
                  cpu_kind: shared
                  cpus: 1
                  memory_mb: 256
                image: nginx:alpine
                name: molecule-worker
                region: ord

scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
