---
- name: Ensure flyio ip addresses are batched
  tags:
    - ip_addresses
  ansible.builtin.include_tasks:
    apply:
      tags:
        - ip_addresses
    file: include.yml
  loop:
    "{{ q('ansible.builtin.subelements',
          ip_addresses_list,
          'ip_addresses',
          {'skip_missing': true}) |
        batch(ip_addresses_batch) }}"
  loop_control:
    label: "{{ __ip_addresses_list | length }}"
    loop_var: __ip_addresses_list
...
